#![cfg(target_os = "windows")]
//! OpenVINO Whisper provider. Model paths are supplied by the pinned model manager.
use super::{openvino_helper_client::{OpenVinoHelperClient,OpenVinoHelperError,OpenVinoProbe},provider::{TranscriptResult,TranscriptionError,TranscriptionProvider}};
use async_trait::async_trait;
use std::{collections::HashMap,path::{Path,PathBuf},sync::{atomic::{AtomicBool,Ordering},Arc,OnceLock}};
use tauri::{AppHandle,Manager,Runtime};
pub const OPENVINO_WHISPER_PROVIDER_ID:&str="openvinoWhisper";
pub const OPENVINO_WHISPER_DISPLAY_NAME:&str="Intel NPU (OpenVINO Whisper)";
pub const DEFAULT_OPENVINO_WHISPER_MODEL:&str="whisper-small-int8";
static PROVIDERS: OnceLock<tokio::sync::Mutex<HashMap<String, Arc<OpenVinoWhisperProvider>>>> = OnceLock::new();
const WHISPER_LANGUAGE_CODES:&[&str]=&["en","zh","de","es","ru","ko","fr","ja","pt","tr","pl","ca","nl","ar","sv","it","id","hi","fi","vi","he","uk","el","ms","cs","ro","da","hu","ta","no","th","ur","hr","bg","lt","la","mi","ml","cy","sk","te","fa","lv","bn","sr","az","sl","kn","et","mk","br","eu","is","hy","ne","mn","bs","kk","sq","sw","gl","mr","pa","si","km","sn","yo","so","af","oc","ka","be","tg","sd","gu","am","yi","lo","uz","fo","ht","ps","tk","nn","mt","sa","lb","my","bo","tl","mg","as","tt","haw","ln","ha","ba","jw","su"];

fn provider_key(model:&str,model_path:&Path)->String{format!("{}:{}",model,model_path.display())}
pub async fn shutdown_all_openvino_providers(){let providers=match PROVIDERS.get(){Some(cache)=>{let mut cache=cache.lock().await;cache.drain().map(|(_,provider)|provider).collect::<Vec<_>>()},None=>Vec::new()};for provider in providers{provider.shutdown().await;}}
pub struct OpenVinoWhisperProvider{client:Arc<OpenVinoHelperClient>,model:String,model_path:PathBuf,loaded:AtomicBool}
impl OpenVinoWhisperProvider{
 pub async fn init_with_paths(model:impl Into<String>,model_path:PathBuf,cache_dir:PathBuf,helper_path:PathBuf)->Result<Arc<Self>,OpenVinoHelperError>{let model=valid_model(model.into())?;if !model_path.is_dir(){return Err(OpenVinoHelperError::Unavailable(format!("OpenVINO model not installed: {}",model_path.display())))}std::fs::create_dir_all(&cache_dir).map_err(|e|OpenVinoHelperError::Unavailable(format!("cannot create OpenVINO cache directory: {e}")))?;let client=Arc::new(OpenVinoHelperClient::new(helper_path));let probe=client.probe_npu().await?;if !probe.available_devices.iter().any(|d|d.eq_ignore_ascii_case("NPU")){return Err(OpenVinoHelperError::Remote{code:"NPU_UNAVAILABLE".into(),message:"Intel NPU is not available. Update the Intel NPU driver or choose another transcription provider.".into()})}client.load_model(&model,&model_path,&cache_dir).await?;Ok(Arc::new(Self{client,model,model_path,loaded:AtomicBool::new(true)}))}
 pub async fn get_or_init<R:Runtime>(app:&AppHandle<R>,model:impl Into<String>,model_path:PathBuf,cache_dir:PathBuf)->Result<Arc<Self>,String>{let model=model.into();let key=provider_key(&model,&model_path);let cache=PROVIDERS.get_or_init(||tokio::sync::Mutex::new(HashMap::new()));let mut cache=cache.lock().await;if let Some(provider)=cache.get(&key).cloned(){if provider.is_model_loaded().await{return Ok(provider)}}if cache.values().any(|provider|Arc::strong_count(provider)>1){return Err("Another OpenVINO model is currently in use. Stop transcription before switching models.".into())}for (_,provider) in cache.drain(){provider.shutdown().await;}let provider=Self::init_with_paths(model,model_path,cache_dir,helper_path_from_app(app)?).await.map_err(|e|e.to_string())?;cache.insert(key,provider.clone());Ok(provider)}
 pub async fn probe(helper:PathBuf)->Result<OpenVinoProbe,OpenVinoHelperError>{OpenVinoHelperClient::probe(helper).await}
 pub async fn shutdown(&self){self.loaded.store(false,Ordering::Release);self.client.shutdown().await}
 pub fn model_id(&self)->&str{&self.model}
 pub fn model_path(&self)->&Path{&self.model_path}
}
pub async fn evict_model_if_idle(model_id:&str,model_path:&Path)->Result<(),String>{let key=provider_key(model_id,model_path);let Some(cache)=PROVIDERS.get()else{return Ok(())};let mut cache=cache.lock().await;let Some(provider)=cache.get(&key).cloned()else{return Ok(())};if Arc::strong_count(&provider)>2{return Err("The selected OpenVINO model is currently in use. Stop transcription before deleting it.".into())}let provider=cache.remove(&key).expect("provider was present while cache lock was held");drop(cache);provider.shutdown().await;Ok(())}
#[async_trait]impl TranscriptionProvider for OpenVinoWhisperProvider{async fn transcribe(&self,a:Vec<f32>,l:Option<String>)->Result<TranscriptResult,TranscriptionError>{if !self.loaded.load(Ordering::Acquire){return Err(TranscriptionError::ModelNotLoaded)}if a.len()<160{return Err(TranscriptionError::AudioTooShort{samples:a.len(),minimum:160})}let task=if l.as_deref()==Some("auto-translate"){"translate"}else{"transcribe"};let l=map_language(l)?;match self.client.transcribe(&a,l.as_deref(),task).await{Ok(r)=>Ok(TranscriptResult{text:r.text.trim().to_string(),confidence:None,is_partial:false}),Err(e)=>{self.loaded.store(false,Ordering::Release);let detail=self.client.last_diagnostic().await.map(|d|format!("; helper diagnostics: {d}")).unwrap_or_default();Err(TranscriptionError::EngineFailed(format!("{e}{detail}")))}}}async fn is_model_loaded(&self)->bool{self.loaded.load(Ordering::Acquire)}async fn get_current_model(&self)->Option<String>{self.loaded.load(Ordering::Acquire).then(||self.model.clone())}fn provider_name(&self)->&'static str{OPENVINO_WHISPER_DISPLAY_NAME}}
fn valid_model(m:String)->Result<String,OpenVinoHelperError>{match m.as_str(){"whisper-base-int8"|"whisper-small-int8"|"whisper-medium-int8"|"whisper-large-v3-turbo-int4"=>Ok(m),_=>Err(OpenVinoHelperError::Unavailable(format!("unsupported OpenVINO model '{m}'")))} }
pub fn map_language(l:Option<String>)->Result<Option<String>,TranscriptionError>{let Some(l)=l.map(|x|x.trim().to_ascii_lowercase()).filter(|x|!x.is_empty()&&x!="auto"&&x!="auto-translate")else{return Ok(None)};if WHISPER_LANGUAGE_CODES.contains(&l.as_str()){return Ok(Some(l))}let x=match l.as_str(){"german"=>"de","english"=>"en","french"=>"fr","spanish"=>"es","italian"=>"it","portuguese"=>"pt","dutch"=>"nl","polish"=>"pl","russian"=>"ru","ukrainian"=>"uk","turkish"=>"tr","arabic"=>"ar","hindi"=>"hi","japanese"=>"ja","korean"=>"ko","chinese"|"zh-cn"|"zh-tw"=>"zh",_=>return Err(TranscriptionError::UnsupportedLanguage(l))};Ok(Some(x.into()))}
pub fn helper_path_from_app<R:Runtime>(app:&AppHandle<R>)->Result<PathBuf,String>{if let Ok(p)=std::env::var("MEETILY_OPENVINO_HELPER"){let p=PathBuf::from(p);if p.is_file(){return Ok(p)}}let resources=app.path().resource_dir().map_err(|e|e.to_string())?;let dev=PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("binaries");let mut directories=vec![resources,dev];if let Ok(executable)=std::env::current_exe(){if let Some(parent)=executable.parent(){directories.push(parent.to_owned());directories.push(parent.join("resources"));}}let names=["openvino-whisper-helper.exe","openvino-whisper-helper-x86_64-pc-windows-msvc.exe"];for directory in directories{for name in &names{let path=directory.join(name);if path.is_file(){return Ok(path)}}}Err("OpenVINO helper sidecar is missing from the application resources or executable directory".into())}
#[cfg(test)]mod tests{use super::*;#[test]fn every_frontend_language_code_maps(){for code in WHISPER_LANGUAGE_CODES{assert_eq!(map_language(Some((*code).into())).unwrap().as_deref(),Some(*code),"{code}");}}#[test]fn language_mapping_normalizes_aliases_and_auto_modes(){assert_eq!(map_language(None).unwrap(),None);assert_eq!(map_language(Some(" German ".into())).unwrap().as_deref(),Some("de"));assert_eq!(map_language(Some("auto-translate".into())).unwrap(),None);assert!(map_language(Some("Klingon".into())).is_err());}#[test]fn models_are_bounded(){for model in ["whisper-base-int8","whisper-small-int8","whisper-medium-int8","whisper-large-v3-turbo-int4"]{assert!(valid_model(model.into()).is_ok(),"{model}")}assert!(valid_model("large".into()).is_err())}}
